#!/usr/bin/env python

import wx
try:
    import lib as larch
except ImportError:
    import larch

from larch.wx import larchframe

app = wx.PySimpleApp()
frame = larchframe.LarchFrame(None)
frame.Show()
app.MainLoop()


