#!/usr/bin/env python

import wx
try:
    import lib as larch
except ImportError:
    import larch
    # print 'use installed larch'
    
from larch.wxlib import larchframe

app = wx.App()
frame = larchframe.LarchFrame(None)
frame.Show()
app.MainLoop()


