; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Larch
AppVersion=0.9.26
AppPublisher=Matthew Newville, GSECARS,  The University of Chicago
AppPublisherURL=http://xraypy.github.com/xraylarch
AppSupportURL=http://xraypy.github.com/xraylarch
AppUpdatesURL=http://xraypy.github.com/xraylarch
AppCopyright=Copyright (C) 2015 Matthew Newville
DefaultDirName={pf}\Larch
DefaultGroupName=Larch
AlwaysRestart=no
LicenseFile=C:\Program Files\Larch\COPYING

[Tasks]
Name: "desktopicon"; Description: "Create &desktop icons"; GroupDescription: "Additional icons:"; MinVersion: 4,4

[Dirs]
Name: "{userappdata}\larch"

[Files]
Source: "C:\Program Files\Larch\*";      DestDir: "{app}";  Flags: "recursesubdirs"
Source: "C:\Program Files\Larch\README.txt"; DestDir: "{app}"; Flags: isreadme

[Icons]
Name: "{group}\Larch"; WorkingDir: "{userappdata}\larch"; Filename: "{app}\bin\larch.exe";  IconFilename: "{app}\bin\larch.ico";

Name: "{group}\Uninstall Larch"; Filename: "{uninstallexe}"


