REM Setting Path Environmental Variable
@ECHO OFF
PATH=C:/Windows/system32
PATH=%PATH%;C:/Windows
PATH=%PATH%;C:/Windows/System32/Wbem
PATH=%PATH%;C:/Users/xas_user/AppData/Local/Continuum/Anaconda2
PATH=%PATH%;C:/Users/xas_user/AppData/Local/Continuum/Anaconda2/Scripts
PATH=%PATH%;C:/Users/xas_user/AppData/Local/Continuum/Anaconda2/Library/bin
PATH=%PATH%;C:/Users/xas_user/AppData/Local/GitHub/PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11/cmd
PATH=%PATH%;C:/Users/xas_user/AppData/Local/GitHub/PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11/usr/bin
PATH=%PATH%;C:/Users/xas_user/AppData/Local/GitHub/PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11/usr/share/git-tfs
PATH=%PATH%;C:/Users/xas_user/AppData/Local/Apps/2.0/MBTPNXYZ.0MB/YR4YMA95.C0W/gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4
PATH=%PATH%;C:/Users/xas_user/AppData/Local/GitHub/lfs-amd64_1.3.1
PATH=%PATH%;C:/Users/xas_user/AppData/Local/Apps/2.0/MBTPNXYZ.0MB/YR4YMA95.C0W/gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4/NativeBinaries/x86
PATH=%PATH%;C:/Windows/System32/WindowsPowerShell/v1.0/
PATH=%PATH%;
PATH=%PATH%;C:/GnuWin32/bin
PATH=%PATH%;T:/xas_user/bin
PATH=%PATH%;C:/epics/bin/
PATH=%PATH%;C:/Python27
PATH=%PATH%;C:/Python27/Scripts
PATH=%PATH%;C:/Program Files (x86)/Common Files/Rockwell/
PATH=%PATH%;C:/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/
PATH=%PATH%;C:/Program Files/Microsoft SQL Server/110/Tools/Binn/
PATH=%PATH%;C:/Program Files (x86)/Microsoft SDKs/TypeScript/1.0/
PATH=%PATH%;C:/Program Files/caQTDM/bin/windows-x64/
PATH=%PATH%;C:/Users/xas_user/AppData/Roaming/DemeterPerl/perl/bin
PATH=%PATH%;C:/Users/xas_user/AppData/Roaming/DemeterPerl/perl/site/bin
PATH=%PATH%;C:/Users/xas_user/AppData/Roaming/DemeterPerl/c/bin
PATH=%PATH%;C:/epics
PATH=%PATH%;C:/Program Files (x86)/MSBuild/12.0/bin/
PATH=%PATH%;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.1A/bin/NETFX 4.5.1 Tools/x64
PATH=%PATH%;C:/Program Files (x86)/Microsoft SDKs/F#/3.1/Framework/v4.0/
